apiVersion: ENC[AES256_GCM,data:TMM=,iv:x2AwAeSYPUOoZjp3Y6CJZclC5eafmOHgtfjGcKk52wk=,tag:pAwt+LxqdSIldJXgayEXeQ==,type:str]
kind: ENC[AES256_GCM,data:xkhC+gEs,iv:jmaz6DQ8sQheocLkZWZcPGTNcGmfxyuaYBD2w+M5Y+c=,tag:WLos5eYZz9VA6NpwMzmXdg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YXvy+V/oSNCPcY4=,iv:684onfJKyfwsRr/FU0eA4JYWcYxPLT8sVBAjmJA2u5c=,tag:LwFLFZpJxyQy3S/qlZKoAQ==,type:str]
stringData:
    robbert-key: ENC[AES256_GCM,data:Rc1LBWByyKiu0iXUCiBIsZudAbCQXhw=,iv:ZJXfvIA1+s7h5iagSETHtB471I/YNVsi+3Z7RDoOLOE=,tag:u1bQ+IG2zamikmOM/Oq9aA==,type:str]
sops:
    age:
        - recipient: age1fdup3p822e4qd3jexcpsqq7nrqsrrmvmu4c22p0s9qlxc93dkplqd0xj0j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb3E4ODliU3l6U0FnVEVB
            RThYRzk0RDJaRTNxUjNKT2grYURrM0hKWENBCnRlRmdUeVhoWENGZVdlWS9tUlVO
            QU1LNFpSSlZ3dXJ2Zno0VHlFTHRINWsKLS0tIFNRY04zVFhLY3poU0IxenRvRGh0
            TnlSdmhUNWVUOFQzRE5qeGpjMEMrS00K8ILdXU+AVyhMAhxGRqj7Mp5YeBiBMYoy
            37F8l8E+dnDxuW6vCxlVAlM7c2Fh9nWlVZPNpfsNf8Vqqv2pTgRZlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-19T09:08:29Z"
    mac: ENC[AES256_GCM,data:Us/iIaCUYQh2a7eJAJH9E3fTh2zxKhsh81mhHK9qIl0r7aSfgPg9tftUlNn4jTGJnyN6TGQKUbh8Os1AP1xIpWSFu8hvYWcxDBmY5DG40DGuePaB9laQ+EkspxmtQYux/JUWHwapE9qMrET3BN9hMJtiuGEBO2F+rSY8AYj76nI=,iv:cKOy8K6vqV6ZSbfY0MXHQl8y5iKF5thRTpHCGnptlvg=,tag:WAtV4ztKO6xDO36kGWhZWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
