package main

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// probe_spec.json is generated by scripts/generate_probe_spec.py from OPI's own
// service registry and embedded at build time, so what this image tests tracks
// the platform automatically. See features/e2e-allservices-image.md.
//
//go:embed probe_spec.json
var probeSpecJSON []byte

// specVersion is the probe-spec structural version this binary understands. A
// mismatch means the spec format changed under the binary; fail loudly.
const specVersion = 1

// Spec is the embedded probe specification.
type Spec struct {
	Version int      `json:"version"`
	Targets []Target `json:"targets"`
}

// Target is one probe: a platform resource to round-trip, with the full set of
// env vars the platform injects for it.
type Target struct {
	ID   string `json:"id"`   // stable status key, e.g. "postgres", "storage-data"
	Kind string `json:"kind"` // probe handler: sql|redis|s3|oidc|path|metadata
	// Services contributing to this target (traceability only).
	Services []string `json:"services"`
	// BoundWhenAny lists the env vars whose presence marks the target bound.
	BoundWhenAny []string `json:"bound_when_any"`
	// EnvVars is every var the platform injects for this target; all must be
	// present (non-empty) once the target is bound.
	EnvVars []string `json:"env_vars"`
}

// loadSpec parses and validates the embedded spec.
func loadSpec() (*Spec, error) {
	var s Spec
	if err := json.Unmarshal(probeSpecJSON, &s); err != nil {
		return nil, fmt.Errorf("parsing embedded probe_spec.json: %w", err)
	}
	if s.Version != specVersion {
		return nil, fmt.Errorf("probe spec version %d, this binary expects %d", s.Version, specVersion)
	}
	if len(s.Targets) == 0 {
		return nil, fmt.Errorf("probe spec has no targets")
	}
	return &s, nil
}
